amqp:
  admin:
    auto-create: false
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

keycloak:
  realm: fc3-coldflix
  host: http://test:8443/

mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:${mysql.port}

logging:
  level:
    root: info

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
