name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'modulos/**'
  workflow_dispatch:

env:
  IMAGE_NAME: fernandonkgw/fc3-admin-catalogo

jobs:
  # Job para a execucao dos testes
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # Configuracao de passos do nosso job
    steps:
      # 1. Check-out do codigo fonte
      - uses: actions/checkout@v3
      # 2. Configurar aJDK na maquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      # 3. Executar os testes da aplicacao.
      - name: Run application tests
        run: ./gradlew test

  # Job para buildar a aplicacao
  build:
    name: Build runner
    needs: tests
    runs-on: ubuntu-latest
    # Configuracao de passos do nosso job
    steps:
      # 1. Check-out do codigo fonte
      - uses: actions/checkout@v3
      # 2. Configurar aJDK na maquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      # 3. Valida a existencia do gradle wapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      # 4. Realizar a build para gerar o artefato final
      - name: Build da aplicacao
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build -x test
      # 5. Definir a variavel branch name
      - name: Set BUILD_TAG
        run: |
          echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV
      # 6. Print BUILD_TAG
      - name: Print BUILD_TAG defined
        run: |
          echo "Branch      ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run number  ---> ${{ github.run_number }}"
          echo "Tag         ---> ${{ env.BUILD_TAG }}"
      # 7. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      # 8. Build & Deploy da imagem
      - name: Build & push da imagem do docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.BUILD_TAG }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}